import Head from 'next/head'

import Footer from '../components/Footer/index'
import Frame from '../components/Frame'
import TeamListBar from '../components/TeamListBar'
import NavBar from '../components/NavBar/index'

export default function Home () {
  return (
    <div>
      <Head>
        <title>NBA-App</title>
        <link rel='icon' href='/Logo-NBA.png' />
        <meta
          name='description'
          content='Generated by create next app'
        />
      </Head>
      <NavBar teamName='Logo-NBA' />
      <TeamListBar />
      <Frame
        teamName='NEWS'
        news={[]}
        imagesUrls={[]}
      />
      <Footer />
    </div>
  )
}
