import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Footer from '../components/Footer/index'
import Frame from '../components/Frame'
import MenuBar from '../components/MenuBar/index'
import TeamListBar from '../components/TeamListBar'
import { NavBar } from '../styles/pages/LandingPage'

export default function Home () {
  return (
    <div>
      <Head>
        <title>NBA-App</title>
        <link rel='icon' href='/Logo-NBA.png' />
        <meta
          name='description'
          content='Generated by create next app'
        />
      </Head>
      <NavBar>
        <Link href='/'>
          <Image src='/app-logo/Logo-NBA.png' width={100} height={57} alt='logoNBA' priority />
        </Link>
        <MenuBar teamName='Logo-NBA' />
      </NavBar>
      <TeamListBar />
      <Frame
        teamName='NEWS'
        news={[]}
        imagesUrls={[]}
      />
      <Footer />
    </div>
  )
}
