import Head from "next/head";
import Image from "next/image";

export default function Home() {
    return (
        <div>
            <Head>
                <title>NBA-App</title>
                <link rel="icon" href="/Logo-NBA.png" />
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <div>hola</div>
        </div>
    );
}
