import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import MenuBar from '../components/MenuBar/index'
import { NavBar } from '../styles/pages/LandingPage'
import TeamListBar from '../components/TeamListBar'
// import Frame from '../components/Frame'
import { Layout } from '../styles/pages/news'

export default function News (props) {
  const news = props.news
  console.log(props)
  return (
    <div>
      <Head>
        <title>NBA-App</title>
        <link rel='icon' href='/Logo-NBA.png' />
        <meta
          name='description'
          content='Generated by create next app'
        />
      </Head>
      <NavBar>
        <Link href='/'>
          <Image src='/app-logo/Logo-NBA.png' width={100} height={57} alt='logoNBA' priority />
        </Link>
        <MenuBar teamName='Logo-NBA' />
      </NavBar>
      <TeamListBar />
      {news.map((el, i) => {
        return (
          <Layout key={i}>
            <h1>{el.title}</h1>
          </Layout>
        )
      })}
    </div>
  )
}

// export async function getStaticProps () {
//   const { data } = await axios.get('https://www.hispanosnba.com/equipos/atlanta-hawks/plantilla')
//   const $ = cheerio.load(data)
//   const html = $('.tblsaleq').text()
//   return {
//     props: { html },
//     revalidate: 10 // rerun after 10 seconds
//   }
// }

export async function getServerSideProps () {
  const headersList = {
    Accept: '*/*',
    'User-Agent': 'Thunder Client (https://www.thunderclient.com)',
    'X-RapidAPI-Key': 'e8079d9059mshaf2885320dead3bp16650ejsne54672d3a921'
  }
  const response = await fetch('https://nba-latest-news.p.rapidapi.com/articles?source=nba', {
    method: 'GET',
    headers: headersList
  })
  const news = await response.json()
  console.log(news)
  return {
    props: {
      news
    }
  }
}
