import { useRouter } from 'next/router'

import Head from 'next/head'
import Image from 'next/image'
import MenuBar from '../../components/MenuBar/index'
import { NavBar } from '../../styles/pages/LandingPage'
import TeamListBar from '../../components/TeamListBar'
import Link from 'next/link'

export default function Home ({ id }) {
  const router = useRouter()
  const { query } = router
  const teamSplited = (query.id).split(' ')
  return (
    <div>
      <Head>
        <title>NBA-App</title>
        <link rel='icon' href='/Logo-NBA.png' />
        <meta
          name='description'
          content='Generated by create next app'
        />
      </Head>
      <NavBar>
        <Link href='/'>
          <Image src='/app-logo/Logo-NBA.png' width={100} height={57} alt='logoNBA' priority />
        </Link>
        <MenuBar teamName={teamSplited[teamSplited.length - 1]} />
      </NavBar>
      <TeamListBar />
    </div>
  )
}

Home.getInitialProps = async ({ query }) => {
  return { id: query.id }
}
