import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import Frame from '../../components/Frame'
import Footer from '../../components/Footer/index'
import MenuBar from '../../components/MenuBar/index'
import TeamListBar from '../../components/TeamListBar'
import { NavBar } from '../../styles/pages/LandingPage'

export default function News ({ id }) {
  const router = useRouter()
  const { query } = router
  let teamSplited = (query.id).split(' ')
  teamSplited = teamSplited[teamSplited.length - 1]

  return (
    <div>
      <Head>
        <title>NBA-App</title>
        <link rel='icon' href='/Logo-NBA.png' />
        <meta
          name='description'
          content='Generated by create next app'
        />
      </Head>
      <NavBar>
        <Link href='/'>
          <Image src='/app-logo/Logo-NBA.png' width={100} height={57} alt='logoNBA' priority />
        </Link>
        <MenuBar teamName={teamSplited} />
      </NavBar>
      <TeamListBar />
      <Frame
        teamName={teamSplited}
        news={[]}
        imagesUrls={[]}
      />
      <Footer />
    </div>
  )
}

News.getInitialProps = async ({ query }) => {
  return { id: query.id }
}
